# Generated by Django 2.2.4 on 2020-11-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_auto_20200210_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='achievements',
            new_name='activites',
        ),
    ]
